.PHONY: all
all: 1-intro.html 2-get-data.html 3-data-structures.html 4-data-types.html 5-tidy-data.html 6-dplyr-data.html 7-quickplots.html 8-ggplot.html

# teacher
1-intro.html: ${@:.html=.Rmd} 1-intro.Rmd
2-get-data.html: ${@:.html=.Rmd} 2-get-data.Rmd
3-data-structures.html: ${@:.html=.Rmd} 3-data-structures.Rmd
4-data-types.html: ${@:.html=.Rmd} 4-data-types.Rmd
5-tidy-data.html: ${@:.html=.Rmd} 5-tidy-data.Rmd
6-dplyr-data.html: ${@:.html=.Rmd} 6-dplyr-data.Rmd
7-quickplots.html: ${@:.html=.Rmd} 7-quickplots.Rmd
8-ggplot.html: ${@:.html=.Rmd} 8-ggplot.Rmd

include ~/lib/common.mk
